server:
  port: 8090

spring:
  application:
    name: realestate
  datasource:
    url: jdbc:mysql://localhost/bootcamp2025
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
