server:
  port: 8090

spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost/bootcamp2025
    username: ${user}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update